dist: trusty
language: java
branches:
  only:
  - master
  - dev
  - "/feature-*/"
  - "/\\d+.\\d+.\\d+/"
  - "/\\d+.\\d+.\\d+-staging/"
addons:
  apt:
    packages:
    - python3
    - python3-pip
    - node
    - docker
before_install:
- gem install fpm --version 1.10.0
- pip3 install --user --upgrade pip virtualenv
- virtualenv -p python3 venv
- source venv/bin/activate
- pip3 install -r jobson-docs/requirements.txt
script: mvn package
env:
  global:
  # travis encrypt GH_TOKEN=tok
  - secure: at1grzYy9RfcIfmoACdaSiY+u+RBDGfk07jCAB2Bn8bEohv21Ny45Is4F3G6Nb9XN7LJdM+6cVINBdsTOKQlIIo0t6nD0sMfkb9IvFP5waDodjTu9Bb8hW2b/7Ul49ANQBErB5f0HxioqGnXvZvrln9UM2Dcml6Sa+1TR+OAkO79cWbiOfRyNbXbC2B1RNl8JNfFOhMhQF/8zE2hpVVW8BQX3V7cBQ+pxLP7X8qEbmifg4HlAkPP31PZn1wIlfdBFG57ODiEWOobO/MkrpbW4V+SAgJkZgW797XbmsE5CUhrtQWiYvze4ZsBknIdSDgD7AXYUDtvJW17jQXFvI5dA8YYdmJfiV5iGRFgMq+5I/1WnSg0OD82NNdYK9YnDKXwjnKObFR5CPJEITT5dMKLnNGSZnTawAfIqXr7rlxETF6UwzMVQl9rvPMK29x3TeqjOgwTVL+MsC0iIkDrh2QGQgzEn1nmfiTHMXLh4nARWoe7q01AfXM5zcp0jhib6yjwQjqT4kc8BQ8SiVLxZq8qD6TQhi7cnCjKaAw9gadJ1cKaNp4dJNsSfMa9oq1LhwukcaZ6VHJIwY9OSVnvC3o4EC+lTfwmztJy/neuZ9h7q71O7MZ6JYRXS+IX4h/ubeV9l6V2yFdgfbb3noNzHs5i39bPa2li89JOoIPMZzpPepc=
deploy:
  provider: releases
  skip_cleanup: true
  file:
  - jobson/target/jobson-${TRAVIS_TAG}.jar
  - jobson-swagger/target/jobson-swagger-${TRAVIS_TAG}.json
  - jobson-ui/target/jobson-ui-${TRAVIS_TAG}.tar.gz
  - jobson-docs/target/jobson-docs-${TRAVIS_TAG}.tar.gz
  - jobson-nix/target/jobson-nix-${TRAVIS_TAG}.tar.gz
  - jobson-deb/target/jobson_${TRAVIS_TAG}_all.deb
  on:
    repo: adamkewley/jobson-1.0-throwaway
    tags: true
  api-key:
    secure: Lt3KHY0yHJe//hpEeoeWAxhp1HrIppaT9EWZUNfA/fHvtiFYLj3ng0T5lsrpG1BQvAclVlGH1yq6PRo+ymKeG4jHAmlfxj4y9sGueBI/rTvOozPHDChBqbMrp5R0LdaH8uHZEzmeUhWJ13hcFbGaCqAPkiEHafV8q5Bu7rM4HH/A4Ah/ltvcF+efWJuOfRPZ7ccpYRR9KhCN4VkN3+AwrHBSgYw8MMIgwRAaDC4KLTrdzYD+3vG+TeKZxQ9z+LDhbzQT61bqaTJK9cWLyCRysouU1wVcGQ7+Un25c7eJqXBrHGHfnynzuHNCOueLaJtJz4Y8pmsnTfuhc003mOGm7v+hQhNx7oYHXozCIxHjjc2o2JTOHoll1wC9TNBijLR1bWx5iBgVt0CaIyvNwpXgJlwZ7VYSNH4fNF760X4way6FovG17m3XL6ql9tEoO2dQwsefZHQk+xgppm5hpncRWfsE29WS9KT+copvAO/RYEA3mlL3kUhCpPpGqxqt7bwY3s43bb3DqTeeyD+TSdd4KZb7hVVyCWEuukOgMxbtVAQmaBhMitxmFdryyDT9liF53Og1KmtcR7TjQz9sWkJ/CfsUfdUV8CS1JPKRcPCPtmKtlXt8J/GjGagGFryJHn2mgsLvxv8ZZYGx4o1iInzGxRhMpx8hl4aRhHkuAMD9CZM=
after_deploy: |
  set -e
  
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"

  git fetch origin gh-pages:gh-pages
  git worktree add gh-pages gh-pages

  rm -rf gh-pages/*
  tar xfz jobson-docs/target/jobson-docs-${TRAVIS_TAG}.tar.gz
  mv jobson-docs-${TRAVIS_TAG}/* gh-pages

  cd gh-pages
  touch .nojekyll
  git add -A
  git commit -m "Updated docs for ${TRAVIS_TAG}"
  git remote add origin-pages https://${GH_TOKEN}@github.com/adamkewley/jobson-1.0-throwaway.git > /dev/null 2>&1
  git push origin-pages gh-pages

  
