dist: trusty

language: java

branches:
  only:
  - master
  - dev
  - /feature-*/  # feature branches
  - /\d+.\d+.\d+/  # tagged versions
  - /\d+.\d+.\d+-staging/  # staging area for tagged releases

addons:
  apt:
    packages:
    - python3
    - python3-pip
    - node
    - docker

before_install:
- gem install fpm --version 1.10.0  # for creating OS packages
- pip3 install --user --upgrade pip virtualenv
- virtualenv -p python3 venv
- source venv/bin/activate
- pip3 install --user -r jobson-docs/requirements.txt


script: mvn package

env:
  global:
    # GH_TOKEN=...
    secure: "Y1TAIbGjkgL9VAuVfCMepY3JvpkLzhqJ0yVQOsRZohN3Tm/6W3uc0c+AkAzmfrH8yuMtzT51NPytETc5xyIwNTWrFZsCxcu2mpiLhufQpmajWmq/pZ08jvnamsyrO8L33IYiz+mYTJiYdEXvCH657HdhVaXWtGhwyEXPEDxN6NxiX6gNxi+hDi30eJoljro3wfld2Me5sYQSkICF1W/gg7z/knG0am4NpIJJoJLnp3lVwFubLvBTOHq1lq/INctOmFSs46mM0QXqqfVTXuFjfzER+vf4zsS9/DQkYEQzsYrbb6YcdVI/m8llci8MphOZnmq/0e0X5rEu43s5WTEl2XaH5pgtGPPAKk5h6NgwuZWxBOfrjE5GLOJ81ZXhrtu4cjMb77U+I+L0xVDSXXJPBP5FhUyBO9wMwrJpW8Gmz6gIrPF1q+DC5BNm7c/2InTev0T6IotdlWM0JjpbSjtVsLlcAL7M7IaFP3PoEs+ruX2DCLLTKFPszphNvWfiDSCGf9pOcF3EXhmJN0UDBl5feves5xkOZ/2gHHuoZMk/4pVvmMpappMkBqVSI37oHu9C1WsMrv9awfBnEb8gj1/d9yM8oXMWXtgxyfdDo/4Of5BfFghsgMPq+7LXg3HYs8fCwb5ew4/qqWVesWAgInOwN0zT0X+G/SbAnj7LZxZ/mjg="

deploy:
  provider: releases
  api_key:
    secure: "IuTc3Q/ihO3BTSS9nCK3QLFC/24Oxm57TwLypftTsj8m/Npre5w35OzgGLWGcvxXNEEhDL3W/cQ2seidcCKFdrxjv9QySEkK9WtJ1kz8MzYzhV2bXlFqgKi0vVMkeEjc08H2CGPX9x3dlkHY3HBeixOY08RVhb1JEf1/igW9cjV9LG+W4zFVqlmp/3hSB2XRXezof0ezDWJtlMR7t0yOGQ25GvQq2XULm/bz8jf/quEO3I7Gr0cwPk6gw7qD7sdXLZ6qCnawVjQXnxd6aJAg66hkEsFC68R/+r0eitZKa9n1U7dWRkf8QB72NVUgPcCWmFW4iIld/bZFsN5o6CcvRMbRxoT9bDzZG6qUAaggt1WcffjpE9CGnz/kM5uvzDV7gPFdf7yKwoe1cuanrxk3HWpUPK5cEKpaFexjTzMHowo7iRuOIuXpK26zPNKf70KTa6fILCa4TQ27vjnWw3mEkoC8dYq1t4pmdvGR7u7UjrNm8HI2dOoEtktiDXhehkk9PFT+yvo6XR1h7vKjiEA2s8tXCsgfCgmAELqSIHT+Tba4smCjEKhItU56V8QzxAdLVHD65yQ5zK7w+3HAeoPd2CdZvgvRkvttV/l31zKrb9BeIadgqaVtNtfrZbwJh9fmaRcgpODI+wrFdCRrHZH58C/L5owYg2KpaWMfG+Y9WVA="

  skip_cleanup: true

  file:
  - jobson/target/jobson-${TRAVIS_TAG}.jar
  - jobson-deb/target/jobson_${TRAVIS_TAG}_all.deb
  - jobson-nix/target/jobson-nix-${TRAVIS_TAG}.tar.gz
  - jobson-docs/target/jobson-docs-${TRAVIS_TAG}.tar.gz
  - jobson-swagger/target/jobson-swagger-${TRAVIS_TAG}.json
  - jobson-swagger-ui/target/jobson-swagger-ui-${TRAVIS_TAG}.tar.gz
  - jobson-ui/target/jobson-ui-${TRAVIS_TAG}.tar.gz

  on:
    tags: true

# Update documentation site
after_deploy: |
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"

  git fetch origin gh-pages:gh-pages
  git worktree add gh-pages gh-pages

  rm -rf gh-pages/*
  tar xfz jobson-docs/target/jobson-docs-${TRAVIS_TAG}.tar.gz
  mv jobson-docs-${TRAVIS_TAG}/* gh-pages

  cd gh-pages
  git add -A
  git commit -m "Updated docs for ${TRAVIS_TAG}"
  git remote add origin-pages https://${GH_TOKEN}@github.com/adamkewley/jobson.git > /dev/null 2>&1
  git push origin-pages gh-pages
